### ISSUE TITLE
Change voice?

### ISSUE THREAD

**Issue by ghost** [junosuarez/node-flite#2]
I'm having trouble understanding how to change the voice,
Could you provide an example?

**Comment by junosuarez** [comment]
Thanks for the question!

Since the voices available depend on the `flite` binary, you first have to get the available voice names:

``` js
flite(function (err, speech) {
  if (err) { return console.error(err) }
  console.log('Available voices:', speech.voices);
})
```

for example, in the default source distribution of flite linked from the readme, compiled and running on my machine, I get:

```
Available voices: [ 'kal', 'awb_time', 'kal16', 'awb', 'rms', 'slt' ]
```

then, pass the voice string you want into the optional `config` argument:

``` js
flite({voice: 'awb'}, function (err, speech) {
  if (err) { return console.error(err) }
  speech.say('hello in voice `awb`!', function (err) {
    if (err) { console.error(err) }
  });
});
```

Hope this helps, let me know if you have any questions! I know the readme and the module itself haven't been updated in a while. I first made this when I was experimenting with RaspberryPI and wanted a small speech synthesis module for node on low-power devices. Cheers!

**Comment by ghost** [comment]
Thank you!, I've been looking for a "free/open source" tts but couldn't find a good one besides flite.
Got it up and running now :D.
Thanks again.
